import { CONFIG } from '../config.js';

export const appState = {
    leafletMap: null,
    bgMode: 'osm',
    radiusMeters: CONFIG.DEFAULT_RADIUS,
    rotation: 0,
    showHex: true,
    showCenters: true,
    showCircles: false,
    buildEnabled: false,
    bsModeEnabled: false,
    moveGridEnabled: false,
    isDragging: false,
    dragStartPixelX: 0,
    dragStartPixelY: 0,
    dragStartLat: 0,
    dragStartLng: 0,
    originalMarkerValues: null,
    objectModeEnabled: false,
    objects: [],
    leafletObjectMarkers: [],
    currentObjectData: null,
    tempObjectMarker: null,
    editingObjectId: null,
    selectedObjectId: null,
    isDraggingObject: false,
    draggedObjectId: null,
    originalObjectValues: null,
    globalShowCircle: false,
    globalCircleRadius: CONFIG.DEFAULT_BS_RADIUS,
    editingZoneId: null,
    originalZoneValues: null,
    zoneModeEnabled: false,
    zones: [],
    currentPolygon: [],
    tempPolygonLayer: null,
    tempPoints: [],
    selectedZoneId: null,
    currentZoneColor: null,
    zoneColorIndex: 0,
    gridCenterLat: null,
    gridCenterLng: null,
    activeHexes: new Map(),
    possibleHexes: new Map(),
    bsMarkers: [],
    leafletMarkers: [],
    currentMarkerData: null,
    currentClickPosition: { x: 0, y: 0 },
    tempMarker: null,
    editingMarkerId: null,
    isDraggingMarker: false,
    draggedMarkerId: null,
    previewCircle: null,
    isMapChanged: false,
    selectedBsId: null,
    mouseMoveTimeout: null,
    lastMouseMoveTime: 0
};
